"""add task priority and due_at

Revision ID: 0b17ff20bbaa
Revises: 3807918a6db1
Create Date: 2026-07-20 00:48:06.779009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b17ff20bbaa'
down_revision: Union[str, Sequence[str], None] = '3807918a6db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=False, server_default='normal'))
    op.add_column('tasks', sa.Column('due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_at')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
