"""add recurrence to tasks

Revision ID: 1abea4240dd7
Revises: 0b17ff20bbaa
Create Date: 2026-07-27 17:43:33.603520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abea4240dd7'
down_revision: Union[str, Sequence[str], None] = '0b17ff20bbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence')
    # ### end Alembic commands ###
